# Bab 8 Backpropagation

## Praktikum

### a) Fungsi *Binary Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [1]:
import pandas as pd

In [2]:
def bin_enc(lbl):
  mi = min(lbl)
  length = len(bin(max(lbl) - mi + 1)[2:])
  enc = []
  for i in lbl:
    b = bin(i - mi)[2:].zfill(length)
    enc.append([int(n) for n in b])
  return enc

def bin_dec(enc, mi=0):
  lbl = []
  for e in enc:
    rounded = [int(round(x)) for x in e]
    string = ''.join(str(x) for x in rounded)
    num = int(string, 2) + mi
    lbl.append(num)
  return lbl

### b) Percobaan *Binary Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [3]:
labels = 1, 2, 3, 4
enc = bin_enc(labels)
dec = bin_dec(enc, min(labels))
print(enc)
print(dec)

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1]]
[1, 2, 3, 4]


### c) Fungsi *One-hot Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:


In [4]:
import numpy as np

def onehot_enc(lbl, min_val=0):
  mi = min(lbl)
  enc = np.full((len(lbl), max(lbl) - mi + 1), min_val, np.int8)
  for i, x in enumerate(lbl):
    enc[i, x - mi] = 1
  return enc

def onehot_dec(enc, mi=0):
  return [np.argmax(e) + mi for e in enc]

### d) Percobaan *One-hot Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [5]:
labels = 1, 2, 3, 4
enc = onehot_enc(labels)
dec = onehot_dec(enc, min(labels))
print(enc)
print(dec)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[1, 2, 3, 4]


### e) Fungsi Aktivasi Sigmoid dan Derivatifnya

Tulis kode ke dalam *cell* di bawah ini:

In [6]:
def sig(X):
  return [1 / (1 + np.exp(-x)) for x in X]

def sigd(X):
  output = []
  for i, x in enumerate(X):
    s = sig([x])[0]
    output.append(s * (1 - s))
  return output

## Soal

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('data/iris.csv')
df.head()

sepallength  sepalwidth  petallength  petalwidth        class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [9]:
kelas = df[df.columns[-1]].astype('string')
kelas

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: class, Length: 150, dtype: string

### Binary encoder & decoder

In [10]:
def bin_enc_str(kelas):
  lbl_num = pd.factorize(kelas)[0]
  lbl_rev = pd.factorize(kelas)[1]
  mi = min(lbl_num)
  length = len(bin(max(lbl_num) - mi + 1)[2:])
  enc = []
  for i in lbl_num:
    b = bin(i - mi)[2:].zfill(length)
    enc.append([int(n) for n in b])
  return enc,lbl_rev

def bin_dec_str(enc,lbl_rev,mi=0):
  lbl = []
  lbl_str = []
  for e in enc:
    rounded = [int(round(x)) for x in e]
    string = ''.join(str(x) for x in rounded)
    num = int(string, 2) + mi
    lbl.append(num)
  for xx in range(len(lbl)):
    lbl_str.append(pd.factorize(lbl_rev)[1][lbl[xx]])
  return lbl_str

### Percobaan binary encoding & decoder

In [11]:
enc_bin,lbl = bin_enc_str(kelas)
dec_bin = bin_dec_str(enc_bin,lbl)

In [14]:
df_bin = pd.concat([pd.DataFrame(enc_bin).reset_index(drop=True),pd.DataFrame(dec_bin,columns=['kelas']).reset_index(drop=True)], axis = 1)
df_bin

0  1           kelas
0    0  0     Iris-setosa
1    0  0     Iris-setosa
2    0  0     Iris-setosa
3    0  0     Iris-setosa
4    0  0     Iris-setosa
..  .. ..             ...
145  1  0  Iris-virginica
146  1  0  Iris-virginica
147  1  0  Iris-virginica
148  1  0  Iris-virginica
149  1  0  Iris-virginica

[150 rows x 3 columns]

### One-hot encoder-decoder

In [16]:
import numpy as np
import pandas as pd
def onehot_enc_str(lbl, min_val=0):
  lbl_num = pd.factorize(lbl)[0]
  lbl_rev = pd.factorize(lbl)[1]
  mi = min(lbl_num)
  enc = np.full((len(lbl_num), max(lbl_num) - mi + 1), min_val,np.int8)
  for i, x in enumerate(lbl_num):
    enc[i, x - mi] = 1
  return enc,lbl_num,lbl_rev

def onehot_dec_str(enc,lbl_rev,mi=0):
  lbl = []
  decode_number = []
  for e in enc:
    decode_number.append(np.argmax(e) + mi)
  for xx in range(len(decode_number)):
    lbl.append(pd.factorize(lbl_rev)[1][decode_number[xx]])
  return lbl

### Percobaan one-hot encoder & decoder

In [18]:
enc_oh,lbl_num,lbl_rev = onehot_enc_str(kelas)
dec_oh = onehot_dec_str(enc_oh,lbl_rev,min(lbl_num))

In [20]:
df_oh = pd.concat([pd.DataFrame(enc_oh).reset_index(drop=True),pd.DataFrame(dec_oh,columns=['kelas']).reset_index(drop=True)], axis = 1)
df_oh

0  1  2           kelas
0    1  0  0     Iris-setosa
1    1  0  0     Iris-setosa
2    1  0  0     Iris-setosa
3    1  0  0     Iris-setosa
4    1  0  0     Iris-setosa
..  .. .. ..             ...
145  0  0  1  Iris-virginica
146  0  0  1  Iris-virginica
147  0  0  1  Iris-virginica
148  0  0  1  Iris-virginica
149  0  0  1  Iris-virginica

[150 rows x 4 columns]